default:
    @echo "Please specify a command to run. Available commands:"
    @just -g --list

http-server:
    http-server -S -C ~/.config/mkcert/localhost.pem -K ~/.config/mkcert/localhost-key.pem

super-f1:
		@{{justfile_directory()}}/commands/super-f1.ts

