#!/usr/bin/env sh

# Turn off tiling by default for all apps
yabai -m rule --add app=".*" manage=off

yabai -m rule --add app="^Wispr Flow$" managed=off

yabai -m config layout bsp
yabai -m config window_placement first_child
yabai -m config window_topmost on
yabai -m config mouse_modifier fn

yabai -m signal --add event=window_created action='ymsp window-created'
yabai -m signal --add event=application_launched action='ymsp window-created'

