#!/usr/bin/env sh

yabai -m config layout bsp
yabai -m config window_placement first_child
yabai -m config window_topmost on
yabai -m config mouse_modifier fn

yabai -m signal --add event=window_created action='ymsp window-created'
yabai -m signal --add event=application_launched action='ymsp window-created'

yabai -m rule --add app="^Toggl Track$" scratchpad=toggltrack grid=11:11:1:1:9:9
yabai -m rule --add app="^Wispr Flow$" managed=off

